#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'zsh', :git => 'git://github.com/opscode-cookbooks/zsh.git'
cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'postgresql'
cookbook 'database', :git => 'git://github.com/manuelvanrijn/cookbook-database.git', :ref => 'grant-roles'
cookbook 'nodejs'
cookbook 'build-essential'
cookbook 'libevent', :git => "git://github.com/tk0miya/chef-libevent.git"
cookbook 'tmux', :git => "git://github.com/keenlabs/chef-tmux.git"
cookbook 'vim'
cookbook 'curl', :git => "git://github.com/phlipper/chef-curl.git"
cookbook 'chef-heroku-toolbelt', :git => "git://github.com/rchampourlier/chef-heroku-toolbelt.git"

# before running vagrant up run in chef folder
# librarian-chef install
                                                       ""

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
